import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#4c4542",
        "on-tertiary-fixed-variant": "#4c4542",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#201a18",
        "surface-container-lowest": "#ffffff",
        "secondary": "#5d5f5f",
        "secondary-fixed-dim": "#c6c6c7",
        "on-surface-variant": "#504441",
        "on-surface": "#1b1c1c",
        "surface-tint": "#77574d",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#2c160e",
        "inverse-surface": "#303030",
        "tertiary-fixed-dim": "#cfc4c0",
        "secondary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary-container": "#616363",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ece0dc",
        "status-gold": "#C5A059",
        "surface-container-highest": "#e5e2e1",
        "on-tertiary-container": "#bdb3af",
        "surface-dim": "#dcd9d9",
        "primary-fixed-dim": "#e7bdb1",
        "surface-bright": "#fcf9f8",
        "primary-container": "#5d4037",
        "surface-warm": "#F5F5F5",
        "primary-fixed": "#ffdbd0",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-container": "#d4ada1",
        "outline-variant": "#d4c3be",
        "primary": "#442a22",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-background": "#1b1c1c",
        "surface": "#fcf9f8",
        "tertiary": "#352f2c",
        "surface-container-low": "#f6f3f2",
        "background": "#fcf9f8",
        "surface-container-high": "#eae7e7",
        "inverse-primary": "#e7bdb1",
        "border-subtle": "#E0E0E0",
        "on-primary-fixed-variant": "#5d4037",
        "on-secondary-fixed-variant": "#454747",
        "error": "#ba1a1a",
        "outline": "#827470",
        "surface-container": "#f0eded",
        "secondary-container": "#dfe0e0",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-mobile": "16px",
        "gutter-desktop": "24px",
        "margin-desktop": "auto",
        "margin-mobile": "20px",
        "container-max-width": "1200px",
        "base": "4px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      }
    },
  },
  plugins: [],
};
export default config;
